/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package libdb.subadmin;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author SANEM
 */
public class addBookCopy4 extends javax.swing.JFrame {
    Connection con;
    /**
     * Creates new form addBookCopy4
     */
    public addBookCopy4() {
        initComponents();
    }
    
    public addBookCopy4(Connection c) {
        initComponents();
        this.con = c;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        booktxt = new javax.swing.JTextField();
        booklabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        searchbook = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        booklabel.setText("BOOK NAME");

        jLabel2.setText("PLEASE ENTER THE BOOK NAME TO SEARCH");

        searchbook.setText("SEARCH");
        searchbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchbook, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(booklabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(booktxt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(booklabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(booktxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(searchbook, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbookActionPerformed
        String bk = booktxt.getText();
        String msg = "";
        try {
            Statement st = this.con.createStatement();
            String query = "Select * from bookinfo where title='"+bk+"'";
            ResultSet res = st.executeQuery(query);
            String isbn = "";
            while(res.next()){
                isbn = res.getString("isbn");
            }
            res.close();
            st.close();
            
            String q = "Select * from book where isbn = '"+isbn+"'";
            ResultSet rep = this.con.createStatement().executeQuery(q);
            List<String> lis = new ArrayList();
            while(rep.next()){
                lis.add(rep.getString("bookid"));
            }
            rep.close();
            int len = lis.size();
            List<String> re = new ArrayList();
            for(String s:lis){
                              System.out.println(s);
                String q2 = "Select * from borrow where bookid = '"+s+"'";
                ResultSet rs = this.con.createStatement().executeQuery(q2);
                while(rs.next()){                     
                    if(rs.getString("rdate") == null){                      
                        msg = "A copy is held by a customer and not returned yet";                        
                        re.add(s);
                    }
                }
            }
             for(String e : re){
                 lis.remove(e);
             }
             if(lis.size() > 0){
                for(String s: lis){   
                        String q3 = "Select * from location where bookid = '"+s+"'";
                        ResultSet bs = this.con.createStatement().executeQuery(q3);
                        String br ="";
                        String loc = "";
                        while(bs.next()){
                            String bname = bs.getString("branchid");
                            String q4 = "Select * from branch where branchid = '"+bname+"'";
                            ResultSet rs = this.con.createStatement().executeQuery(q4);
                            
                            while(rs.next()){
                                br = rs.getString("name");
                            }
                            rs.close();
                            loc = bs.getString("position");
                            
                        }bs.close();
                        
                        if(lis.size() < len){
                            dispose();
                            JOptionPane op = new JOptionPane();
                            op.setMessage(msg+" But there are other available copies for you:\nAt branch "+br+" in "+loc);
                            op.setMessageType(1);
                            JDialog dia = op.createDialog(null,"Info");
                            dia.setTitle("BOOK QUERY RESULT");
                            dia.setVisible(true); 
                        }else{
                            dispose();
                            JOptionPane op = new JOptionPane();
                            op.setMessage(" Here are the copies:\nAt branch "+br+" in "+loc);
                            op.setMessageType(1);
                            JDialog dia = op.createDialog(null,"Info");
                            dia.setTitle("BOOK QUERY RESULT");
                            dia.setVisible(true);                          
                        }                        
                }
             }else{
                 
                 dispose();
                  JOptionPane op = new JOptionPane();
                            op.setMessage(" Unfortunately there are no available copies of this book for you.. ");
                            op.setMessageType(1);
                            JDialog dia = op.createDialog(null,"Info");
                            dia.setTitle("BOOK QUERY RESULT");
                            dia.setVisible(true); 
             }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(addBookCopy4.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_searchbookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addBookCopy4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addBookCopy4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addBookCopy4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addBookCopy4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addBookCopy4().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel booklabel;
    private javax.swing.JTextField booktxt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton searchbook;
    // End of variables declaration//GEN-END:variables
}
